[YUNIKORN-1414] Adding Chinese translations of Sorting Policies
apache/yunikorn-site pull request #273
Opened 2023-03-02 08:57 UTC by KatLantyss

### What is this PR for?
Adding Chinese translations of Sorting Policies

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [√] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

2023-03-03 02:19 UTC, yangwwei requested changes

2023-03-03 02:19 UTC, yangwwei commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/sorting_policies.md
> +简短描述：基于使用情况公平排序。
> 基于使用情况公平排序。

基于资源利用率公平性排序

2023-03-03 02:19 UTC, yangwwei commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/sorting_policies.md
> +结果，可用资源平均分配给所有请求资源的应用程序。
> 结果，可用资源平均分配给所有请求资源的应用程序。

达到的效果是资源相对平均分配给所有请求资源的应用程序

2023-03-03 02:19 UTC, yangwwei commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/sorting_policies.md
> +简短描述：限制 Starting 或 Accepted 状态的应用程序为一个（1）。
> 简短描述：限制 Starting 或 Accepted 状态的应用程序为一个（1）。

简短描述：限制同一时间只有一个为 Starting 或 Accepted 状态的应用程序

2023-03-03 02:19 UTC, yangwwei commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/sorting_policies.md
> +在所有运行的应用程序之后，添加一种新的应用程序进行分配。
达到的效果是，已经在运行的应用程序讲优先得到资源。
在所有已运行的应用程序后，逐一调度新的应用程序。

2023-03-04 05:59 UTC, KatLantyss commented
@yangwwei Thanks for review! I have modified the semantics.

2023-03-05 05:56 UTC, yangwwei approved these changes
LGTM

2023-03-05 05:56 UTC, merged