[YUNIKORN-1510] Adding Chinese translation of Go module updatese
apache/yunikorn-site pull request #339
Opened 2023-09-18 11:46 UTC by youxuan0714

### What is this PR for?
Adding Chinese translation of Go module updates

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1510
### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2023-09-27 08:37 UTC, 0yukali0 requested changes
Thanks for this contribution.
This commit is almost done.

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +1. 在调度程序界面中进行更改。
Above comment

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +在更新核心依赖项之前，必须确保调度程序接口更改已完成。
1.core依赖项
2.调度器

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +3. 为调度程序接口[生成新的伪版本](#generate-a-pseudo-version)。
Above comment

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +5. 运行`make test`以确保更改有效。构建将拉取新的依赖项，并且将使用调度程序接口中的更改。
Same

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +    * 将调度程序接口版本引用替换为步骤 3 中生成的版本引用
调度器
Mark the step3 via **word**. 
It will be **步骤 3**.

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +在某些情况下，调度程序接口的引用没有改变。
Same

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +7. 为核心[生成新的伪版本](#generate-a-pseudo-version)
Core

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +    * 将调度程序接口版本引用替换为步骤 3 中生成的版本引用。
调度器
**步骤 3**

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +    * 将core版本引用替换为步骤 7 中生成的版本引用。
**步骤 7**

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +9. 运行`make test`以确保更改有效。构建将拉下新的依赖项，并将使用core和调度程序接口中的更改。
Above

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +如果同时在调度程序接口和/或core中处理多个 PR，则不同的 PR 可能已经应用了更新。
Above

2023-09-27 08:37 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/dependencies.md
> +因此，执行步骤 5 和 8 以确保不存在回归。
**步骤 5** 和 **步骤 8**

2023-09-27 09:26 UTC, youxuan0714 commented
@0yukali0 thanks for the review and suggestions

2023-09-30 04:28 UTC, 0yukali0 approved these changes
+1 LGTM

2023-09-30 04:29 UTC, merged