[YUNIKORN-1511]Adding Chinese translation of Deploy to Kubernetes
apache/yunikorn-site pull request #342
Opened 2023-09-26 13:31 UTC by 0lai0

### What is this PR for?
The Chinese translation for the document Deploy to Kubernetes
https://yunikorn.apache.org/docs/developer_guide/deployment

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
[YUNIKORN-1511]Adding Chinese translation of Deploy to Kubernetes
*https://issues.apache.org/jira/browse/YUNIKORN-1511

### Screenshots (if appropriate)
![image](https://github.com/apache/yunikorn-site/assets/72776271/ee27e041-dd83-40ef-829d-4f0fe120ed10)

2023-10-28 16:52 UTC, 0yukali0 requested changes

2023-10-28 16:52 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +部署YuniKorn的最简单方法是利用我们的[helm charts](https://hub.helm.sh/charts/yunikorn/yunikorn)，您可以在[这里](get_started/get_started.md)找到指南。本文档描述了手动部署YuniKorn调度器和准入控制器的过程，主要面向开发人员。
本文档主要面向开发人员，描述了手动部署YuniKorn调度器和准入控制器的过程。

2023-10-28 16:52 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +**注意** 镜像标记包含您的构建架构。对于Intel，它将是 `amd64`，对于Mac M1，它将是 `arm64v8`。
:::note
1. 默认构建使用硬编码的用户和标签。您 *必须* 更新 `Makefile` 中的 `IMAGE_TAG` 变量，以便推送到正确的仓库。
2. Docker Hub 上使用最新标签之YuniKorn 镜像不再更新，因为 ASF 政策的原因。因此，在部署之前，您应该在本地部署调度器和 Web 镜像。
3. 镜像标记包含您的构建架构。对于Intel，它将是 `amd64`，对于Mac M1，它将是 `arm64`。
:::

2023-10-28 16:52 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +在部署调度器之前，必须执行此操作。它需要一个正确设置的Kubernetes环境。这个Kubernetes环境可以是本地的或远程的。
在部署调度器之前，必须执行此操作，正确设置Kubernetes环境。这个Kubernetes环境可以是本地的或远程的。

2023-10-28 16:52 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +* yunikorn-scheduler-core (yunikorn scheduler core and shim for K8s)
yunikorn-scheduler-core (适用于 K8s 的 yunikorn 调度器核心和shim）

2023-10-28 16:52 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +* yunikorn-scheduler-web (web UI)
yunikorn-scheduler-web (网页UI)

2023-10-28 16:52 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +注意：准入控制器会从用户那里抽象出`schedulerName`和`applicationId`的添加，因此会将所有流量路由到YuniKorn。如果您使用Helm chart进行部署，它将会同时安装准入控制器和调度器。否则，如果运行的工作负载中Pod规范和元数据中没有`schedulerName`和`applicationId`，则可以继续下面的步骤手动部署准入控制器。
:::note
准入控制器会从用户那里抽象出`schedulerName`和`applicationId`的添加，因此会将所有流量路由到YuniKorn
如果您使用Helm chart进行部署，它将会同时安装准入控制器和调度器
否则，如果运行的工作负载中Pod规范和元数据中没有`schedulerName`和`applicationId`，则可以继续下面的步骤手动部署准入控制器。
:::

2023-10-29 06:45 UTC, 0yukali0 commented
In both documents with different languages, replacing ":::note something :::" with "*note* something" marks messages.

2023-11-26 06:30 UTC, steinsgateted requested changes
@0lai0 @0yukali0 Thank you
Update documentation #338

2023-12-11 13:53 UTC, chenyulin0719 requested changes
Some sentences are already outdated. Please update to the latest version. Thanks.

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +
There have new commit after this PR. ( 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48 )
Missing translation of 
> **Note** The primary source of deployment information is the Helm chart, which can be found at [yunikorn-release](https://github.com/apache/yunikorn-release/). Manual deployment may lead to out-of-sync configurations, see [deployments/scheduler](https://github.com/apache/yunikorn-k8shim/tree/master/deployments/scheduler)

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +kubectl create -f scheduler/yunikorn-rbac.yaml
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48

> kubectl create -f deployments/scheduler/admission-controller-rbac.yaml

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +curl -o queues.yaml https://raw.githubusercontent.com/apache/yunikorn-k8shim/master/conf/queues.yaml
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48
> curl -o yunikorn-configs.yaml https://raw.githubusercontent.com/apache/yunikorn-k8shim/master/deployments/scheduler/yunikorn-configs.yaml

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +- 根据需要修改 `queues.yaml` 文件的内容，然后在Kubernetes中创建ConfigMap:
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48

> - modify the content of yunikorn-configs.yaml file as needed, and create ConfigMap in kubernetes:

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +kubectl create configmap yunikorn-configs --from-file=queues.yaml
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48

> kubectl create configmap yunikorn-configs --from-file=yunikorn-configs.yaml

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +kubectl create configmap  yunikorn-configs --from-file=queues.yaml -o yaml --dry-run=client | kubectl apply -f -
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48

> kubectl create configmap yunikorn-configs --from-file=yunikorn-configs.yaml -o yaml --dry-run=client | kubectl apply -f -

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +注意：在资源分配队列规范中使用与yunikorn-defaults配置中使用的文件名相同的文件名，例如 `queues.yaml`。
Removed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +kubectl create -f scheduler/admission-controller-rbac.yaml
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48
> kubectl create -f deployments/scheduler/admission-controller-rbac.yaml

2023-12-11 13:53 UTC, chenyulin0719 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/deployment.md
> +kubectl create -f scheduler/admission-controller-secrets.yaml
Changed in 9a2f4a93d84b2e6c56a1c6e29a2aaaa1d66c3e48
> kubectl create -f deployments/scheduler/admission-controller-secrets.yaml

2024-02-21 23:56 UTC, closed without merging

2024-02-21 23:56 UTC, wilfred-s commented
No longer relevant after [YUNIKORN-2411](https://issues.apache.org/jira/browse/YUNIKORN-2411)