[YUNIKORN-2000]Adding Chinese translation of Architecture
apache/yunikorn-site pull request #345
Opened 2023-09-27 08:57 UTC by 0lai0

### What is this PR for?
The Chinese translation for the document Design of Architecture
in  current development_guide/design/[Architecture](https://yunikorn.apache.org/docs/1.0.0/design/architecture)

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
[YUNIKORN-2000]Adding Chinese translation of Architecture
* [https://issues.apache.org/jira/browse/YUNIKORN-2000](https://issues.apache.org/jira/browse/YUNIKORN-2000)

### Screenshots (if appropriate)
![image](https://github.com/apache/yunikorn-site/assets/72776271/c0c903c5-b2ce-4f29-b3f3-5f26bea0247c)

2023-09-30 14:56 UTC, 0yukali0 requested changes

2023-09-30 14:56 UTC, 0yukali0 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/design/architecture.md
> +以下图表展示了YuniKorn的高级架构。
以下图表展示了YuniKorn的架构。

2023-10-29 05:32 UTC, 0yukali0 approved these changes
+1 LGTM

2023-10-29 05:45 UTC, 0yukali0 requested changes
I noticed some markdown links are broken.
These warning problems should be resolved.
```
[WARNING] Docs markdown link couldn't be resolved: (../design/architecture.md) in "/yunikorn-site/docs/archived_design/k8shim.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../archived_design/scheduler_core_design.md) in "/yunikorn-site/i18n/zh-cn/docusaurus-plugin-content-docs/current/design/architecture.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../archived_design/k8shim.md) in "/yunikorn-site/i18n/zh-cn/docusaurus-plugin-content-docs/current/design/architecture.md" for version current
```

2024-02-21 23:57 UTC, wilfred-s commented
No longer relevant after [YUNIKORN-2411](https://issues.apache.org/jira/browse/YUNIKORN-2411)

2024-02-21 23:57 UTC, closed without merging