[YUNIKORN-2032] Update cluster api document
apache/yunikorn-site pull request #353
Opened 2023-10-13 09:48 UTC by targetoee

### What is this PR for?
The REST API is adjust by [YUNIKORN-959](https://github.com/apache/yunikorn-core/pull/497). We need to update the document also.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
[YUNIKORN-2032](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2032)

2023-10-14 06:00 UTC, steinsgateted requested changes
@targetoee Thank you. NIT:Fix the indent. see: #136 
@wilfred-s Thank you.

2023-10-15 09:52 UTC, targetoee commented
HI @steinsgateted thanks for the reminder. Fix it.

2023-10-15 14:55 UTC, steinsgateted commented
LGTM

2023-10-15 14:57 UTC, steinsgateted approved these changes

2023-10-15 15:00 UTC, merged