[YUNIKORN-2763] add the documentation of REST API for specific queue
apache/yunikorn-site pull request #458
Opened 2024-07-18 13:58 UTC by blueBlue0102

### What is this PR for?
Adds a description about a REST API:
`/ws/v1/partition/{partitionName}/queue/{queueName}`

### What type of PR is it?
* [x] - Documentation

### What is the Jira issue?
[YUNIKORN-2763](https://issues.apache.org/jira/browse/YUNIKORN-2763)

2024-07-18 14:39 UTC, chia7712 approved these changes
LGTM

2024-07-18 16:09 UTC, ryankert01 commented on docs/api/scheduler.md
> +**Code** : `404 Not Found` (Partition not found)
It can also be queue not found or application not found.
see https://github.com/apache/yunikorn-core/blob/master/pkg/webservice/handlers.go#L827

2024-07-18 16:12 UTC, ryankert01 requested changes
Great work! minor nit.

2024-07-18 17:06 UTC, ryankert01 approved these changes

2024-07-21 05:20 UTC, chenyulin0719 approved these changes
LGTM

2024-07-21 05:29 UTC, closed without merging